name: Release

on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: 21
          distribution: oracle

      - name: Read properties
        id: properties
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: gradle.properties
          properties: minecraft_version mod_version

      - name: Build jar
        run: ./gradlew build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.properties.outputs.minecraft_version }}-OneLMod-${{ steps.properties.outputs.mod_version }}.jar
          path: build/libs/OneLMod-${{ steps.properties.outputs.mod_version }}.jar